// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Xml.Api.Data;

#nullable disable

namespace Xml.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828200201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Xml.Api.Models.Building", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Xml.Api.Models.BuildingsRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildingName");

                    b.ToTable("BuildingsRooms");
                });

            modelBuilder.Entity("Xml.Api.Models.Chair", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Chairs");
                });

            modelBuilder.Entity("Xml.Api.Models.Disc", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Discs");
                });

            modelBuilder.Entity("Xml.Api.Models.Event", b =>
                {
                    b.Property<string>("IdSubg")
                        .HasColumnType("text");

                    b.Property<string>("ChairName")
                        .HasColumnType("text");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<string>("DiscName")
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<int>("Less")
                        .HasColumnType("integer");

                    b.Property<string>("PrepId")
                        .HasColumnType("text");

                    b.Property<string>("RoomId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.HasKey("IdSubg");

                    b.HasIndex("ChairName");

                    b.HasIndex("DiscName");

                    b.HasIndex("GroupId");

                    b.HasIndex("PrepId");

                    b.HasIndex("RoomId");

                    b.HasIndex("Week", "Day", "Less");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Xml.Api.Models.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Xml.Api.Models.Prep", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Preps");
                });

            modelBuilder.Entity("Xml.Api.Models.Settings", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Xml.Api.Models.BuildingsRoom", b =>
                {
                    b.HasOne("Xml.Api.Models.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Xml.Api.Models.Event", b =>
                {
                    b.HasOne("Xml.Api.Models.Chair", "Chair")
                        .WithMany("Events")
                        .HasForeignKey("ChairName");

                    b.HasOne("Xml.Api.Models.Disc", "Disc")
                        .WithMany("Events")
                        .HasForeignKey("DiscName");

                    b.HasOne("Xml.Api.Models.Group", "Group")
                        .WithMany("Events")
                        .HasForeignKey("GroupId");

                    b.HasOne("Xml.Api.Models.Prep", "Prep")
                        .WithMany("Events")
                        .HasForeignKey("PrepId");

                    b.HasOne("Xml.Api.Models.BuildingsRoom", "Room")
                        .WithMany("Events")
                        .HasForeignKey("RoomId");

                    b.Navigation("Chair");

                    b.Navigation("Disc");

                    b.Navigation("Group");

                    b.Navigation("Prep");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Xml.Api.Models.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Xml.Api.Models.BuildingsRoom", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Xml.Api.Models.Chair", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Xml.Api.Models.Disc", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Xml.Api.Models.Group", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Xml.Api.Models.Prep", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
